# Generated by Django 5.2 on 2025-05-14 10:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_user_profile',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_upload_path),
        ),
    ]
