# Generated by Django 5.2 on 2025-05-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
