# Generated by Django 5.2 on 2025-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpresendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_permanently_banned',
            field=models.BooleanField(default=False),
        ),
    ]
